name: KBZ_death
main: pl.kubiz247.kbzdeath.KBZ_death
api-version: 1.16
version: 1.0
description: Custom deaths by kubiz
author: kubiz247
softdepend: [LuckPerms]
commands:
  kbzdeath:
    description: KBZ_death admin commands
    usage: /<command> reload
permissions:
  kbzdeath.*:
    description: Full access to KBZ_death commands
    default: op
  kbzdeath.reload:
    description: Allow reload of KBZ_death config
    default: op